# Generated by Django 4.2.2 on 2024-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(default="127.0.0.1", max_length=200)),
                ("port", models.IntegerField(default=8000)),
                ("is_pair", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="NodeQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=200)),
                ("port", models.IntegerField(default=8000)),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.IntegerField(default=8000)),
                ("is_leader", models.BooleanField(default=False)),
            ],
        ),
    ]
