# Generated by Django 4.2.2 on 2024-02-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_node_nodequeue_server"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="is_pair",
        ),
        migrations.AddField(
            model_name="message",
            name="is_replica",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="node",
            name="is_alive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="node",
            name="pair",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.node"
            ),
        ),
    ]
