# Generated by Django 4.2.2 on 2024-01-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=200)),
                ("is_leader", models.BooleanField(default=False)),
                ("is_alive", models.BooleanField(default=True)),
                (
                    "pair",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.node",
                    ),
                ),
            ],
        ),
    ]
