# Generated by Django 4.2.2 on 2024-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="port",
            field=models.IntegerField(default=8000),
        ),
    ]
