name: Django Build and Docker Image

on:
  push:
    branches:
      - main
      - feature/cicd
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd message-broker-server
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django migrations
      run: |
        cd message-broker-server
        python manage.py migrate

    - name: Collect static files
      run: |
        cd message-broker-server
        python manage.py collectstatic --noinput

    - name: Build Docker image
      run: |
        cd message-broker-server
        docker build -t message-broker .

    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: message-broker:latest
      env:
        DOCKER_USERNAME: test
        DOCKER_PASSWORD: test