name: Django Build and Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd message-broker-server/server
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django migrations
      run: |
        cd message-broker-server/server
        python manage.py migrate

    - name: Run Django tests
      run: |
        cd message-broker-server/server
        python manage.py test

    - name: Run integration tests
      run: |
        cd message-broker-server/tests
        bash test_connecting_three_nodes/test.sh
        bash test_connecting_two_nodes/test.sh
        bash test_fault_tolerance/test.sh

    - name: Build Docker image
      run: |
        cd message-broker-server/server
        docker build -t message-broker .

    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: message-broker:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}